//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookShelf
    {
        public int ID_Users { get; set; }
        public int ID_Products { get; set; }
        public string Name_Products { get; set; }
        public Nullable<int> Price_Products { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
