//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassifyOwn
    {
        public int ID_Classify { get; set; }
        public string Name_Classify { get; set; }
        public int ID_Users { get; set; }
    
        public virtual User User { get; set; }
    }
}
