//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID_Users { get; set; }
        public int ID_Product { get; set; }
        public string Content { get; set; }
        public string DateAdded { get; set; }
        public string ID_Comment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
