//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferDetail
    {
        public int ID_OfferDetails { get; set; }
        public int OfferID { get; set; }
        public int ProductID { get; set; }
        public int UserCategoryID { get; set; }
        public double Discount { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual Product Product { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
