//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OfferDetails = new HashSet<OfferDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.BookShelves = new HashSet<BookShelf>();
            this.ClassifyOwnDetails = new HashSet<ClassifyOwnDetail>();
            this.Comments = new HashSet<Comment>();
            this.Comments1 = new HashSet<Comment>();
        }
    
        public int ID_Products { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int CategoryRID { get; set; }
        public int CategorySID { get; set; }
        public string Image { get; set; }
        public int Status { get; set; }
        public string Detail { get; set; }
        public string ShortDetail { get; set; }
        public string BarCode { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Artist { get; set; }
        public string Year { get; set; }
        public string Company { get; set; }
        public string Publisher { get; set; }
        public string Size { get; set; }
        public string Pages { get; set; }
        public string Location { get; set; }
        public int Quantity { get; set; }
        public int Count { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferDetail> OfferDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductCategoriesRoot ProductCategoriesRoot { get; set; }
        public virtual ProductCategoriesSub ProductCategoriesSub { get; set; }
        public virtual ProductStatus ProductStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookShelf> BookShelves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassifyOwnDetail> ClassifyOwnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments1 { get; set; }
    }
}
