//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicDetail
    {
        public int ID_TopicDetails { get; set; }
        public int TopicID { get; set; }
        public string Detail { get; set; }
        public string ShortDetail { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
